apiVersion: v1
kind: ServiceAccount
metadata:
  name: e2e
  namespace: e2e
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: e2e
rules:
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "watch" ]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: e2e
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: e2e
subjects:
  - kind: ServiceAccount
    name: e2e
    namespace: e2e
---
apiVersion: batch/v1
kind: Job
metadata:
  name: e2e
  namespace: e2e
spec:
  template:
    metadata:
      labels:
        app: e2e
    spec:
      serviceAccount: e2e
      containers:
        - name: e2e
          image: replace-img
      restartPolicy: Never
  backoffLimit: 0