apiVersion: v1
kind: Service
metadata:
  name: memcache-headless
  labels:
    app.kubernetes.io/name: memcache
spec:
  clusterIP: "None"
  ports:
    - name: memcache
      port: 11211
      targetPort: memcache
  selector:
    app.kubernetes.io/name: memcache
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcache
  labels:
    app.kubernetes.io/name: memcache
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: memcache
  replicas: 3
  strategy:
    rollingUpdate: {}
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: memcache
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
              - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: memcache
                topologyKey: kubernetes.io/hostname
                weight: 1
      securityContext:
        fsGroup: 1001
      containers:
        - name: memcache
          image: "bitnami/memcached:1.6.15-debian-11-r17"
          imagePullPolicy: "IfNotPresent"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
          env:
            - name: BITNAMI_DEBUG
              value: "true"
          ports:
            - name: memcache
              containerPort: 11211
          livenessProbe:
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            tcpSocket:
              port: memcache
          readinessProbe:
            failureThreshold: 6
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
            tcpSocket:
              port: memcache
